### ISSUE TITLE
command 'restructuredtext.editor.listEditing.onEnterKey' not found

### ISSUE THREAD

**Issue by iugo** [vscode-restructuredtext/vscode-restructuredtext#314]
Please follow [the troubleshooting guide](https://docs.restructuredtext.net/articles/troubleshooting.html) to locate the culprit.

If troubleshooting does not reveal any useful information, provide the following information to create a new issue,

**Environment**
- [x] Extension version: 159.0.0
- [x] Visual Studio Code version: 1.59.1
- [x] Operating System version: macOS 11.5.2
- [ ] Python version:
- [ ] sphinx version:
- [ ] A sample of conf.py or its important fragments:

**Expected behavior**

**Actual behavior**

When editing a document, there is no line break effect after entering enter.

**Detailed Steps to reproduce the problem**

1. Open an rst file.
2. Press the enter.

**Comment by bs-sgr** [comment]
The command 'restructuredtext.editor.listEditing.onBackspaceKey' is broken too.

Message: command 'restructuredtext.editor.listEditing.onBackspaceKey' not found

**Comment by lextm** [comment]
@iugo Due to a conflict in list/table editors, you need to use `Ctrl+Enter` temporarily with release 159.0.0 to break into a new line. I just published release 160.0.0 to resolve this issue.

@bs-sgr Can you provide more information regarding that? I cannot reproduce it. Anyway 160.0.0 will be live soon, and you can test again if the issue has been resolved by then.

**Comment by bs-sgr** [comment]
@lextm thanks for your help. i have tested the new version 160.0.0 and it is still not working. i am going to try to reproduce it and give you more information

**Comment by iugo** [comment]
This problem was resolved in 160.0.0.

**Comment by lextm** [comment]
@bs-sgr If the problem remains on your machine, please open a new issue so that we can track it separately.

**Comment by Marsfan** [comment]
@bs-sgr I was having the same issue. I fixed it by opening the command palette and searching for _Preferences: Open Keyboard Shortcuts_, in the shortcuts window, I then searched for `restructuredtext.editor.listEditing` and removed all of the shortcuts that 
appeared in the results. Everything works fine now, and all of the shortcuts do what I expect.

I suspect that the underlying commands were removed but VS Code did not properly remove the shortcuts for them.

**Comment by bs-sgr** [comment]
@Marsfan thank you very much. your solution works for me too.

**Comment by felixvd** [comment]
I installed v166.0.0 today on Debian 9 and still had to fix this problem.

> I then searched for `restructuredtext.editor.listEditing` and removed all of the shortcuts that appeared in the results. 

To remove the keybindings, I had to copy them to my user file and add a `-` in front of the command. Thanks for the pointer.

**Comment by gonidelis** [comment]
> @bs-sgr I was having the same issue. I fixed it by opening the command palette and searching for _Preferences: Open Keyboard Shortcuts_, in the shortcuts window, I then searched for `restructuredtext.editor.listEditing` and removed all of the shortcuts that appeared in the results. Everything works fine now, and all of the shortcuts do what I expect.
> 
> I suspect that the underlying commands were removed but VS Code did not properly remove the shortcuts for them.

Worked for me too. What a bug.

**Comment by MinchinWeb** [comment]
Also reported here: https://github.com/microsoft/vscode/issues/137465

**Comment by MinchinWeb** [comment]
I've run into the same issue (for both backspace and enter keys) where the error message keeps popping up. However, I have nothing listed in my (personal) keyboard keybindings, although both are listed under the default keybindings, but that file is read-only. I have v176 (the current version?) installed.

**Comment by Kimtaehung123** [comment]
> @bs-sgr I was having the same issue. I fixed it by opening the command palette and searching for _Preferences: Open Keyboard Shortcuts_, in the shortcuts window, I then searched for `restructuredtext.editor.listEditing` and removed all of the shortcuts that appeared in the results. Everything works fine now, and all of the shortcuts do what I expect.
> 
> I suspect that the underlying commands were removed but VS Code did not properly remove the shortcuts for them.

you are my angel,hahahahahaha~Thanks!

**Comment by lextm** [comment]
vscode-markdown lists several options on this kind of issues, https://github.com/yzhang-gh/vscode-markdown#q-error-command-markdownextensiononxxxkey-not-found

**Comment by SoundsSerious** [comment]
Had this issue as well, it was easily remedied by deleting this extension
